// Generated by CoffeeScript 1.12.7
var setup;

setup = function() {
  var a, b;
  createCanvas(600, 600);
  assert((function() {
    var i, len, ref, results;
    ref = [10, 20];
    results = [];
    for (b = i = 0, len = ref.length; i < len; b = ++i) {
      a = ref[b];
      results.push([a, b]);
    }
    return results;
  })(), [[10, 0], [20, 1]]);
  assert((function() {
    var i, len, ref, results;
    ref = [10, 20];
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      a = ref[i];
      results.push(a);
    }
    return results;
  })(), [10, 20]);
  assert((function() {
    var ref, results;
    ref = {
      a: 10,
      b: 20
    };
    results = [];
    for (a in ref) {
      b = ref[a];
      results.push([a, b]);
    }
    return results;
  })(), [["a", 10], ["b", 20]]);
  assert((function() {
    var results;
    results = [];
    for (a in {
      a: 10,
      b: 20
    }) {
      results.push(a);
    }
    return results;
  })(), ["a", "b"]);
  return print((function() {
    var results;
    results = [];
    for (a in range(1000)) {
      results.push(a);
    }
    return results;
  })());
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7QUFDUCxNQUFBO0VBQUEsWUFBQSxDQUFhLEdBQWIsRUFBaUIsR0FBakI7RUFFQSxNQUFBOztBQUFRO0FBQUE7U0FBQSw2Q0FBQTs7bUJBQUEsQ0FBQyxDQUFELEVBQUcsQ0FBSDtBQUFBOztNQUFSLEVBQW1DLENBQUMsQ0FBQyxFQUFELEVBQUksQ0FBSixDQUFELEVBQVMsQ0FBQyxFQUFELEVBQUksQ0FBSixDQUFULENBQW5DO0VBQ0EsTUFBQTs7QUFBUTtBQUFBO1NBQUEscUNBQUE7O21CQUFBO0FBQUE7O01BQVIsRUFBNkIsQ0FBQyxFQUFELEVBQUksRUFBSixDQUE3QjtFQUVBLE1BQUE7O0FBQVE7Ozs7QUFBQTtTQUFBLFFBQUE7O21CQUFBLENBQUMsQ0FBRCxFQUFHLENBQUg7QUFBQTs7TUFBUixFQUF1QyxDQUFDLENBQUMsR0FBRCxFQUFLLEVBQUwsQ0FBRCxFQUFVLENBQUMsR0FBRCxFQUFLLEVBQUwsQ0FBVixDQUF2QztFQUNBLE1BQUE7O0FBQVE7U0FBQTs7O0tBQUE7bUJBQUE7QUFBQTs7TUFBUixFQUFpQyxDQUFDLEdBQUQsRUFBSyxHQUFMLENBQWpDO1NBRUEsS0FBQTs7QUFBTztTQUFBLGdCQUFBO21CQUFBO0FBQUE7O01BQVA7QUFUTyIsInNvdXJjZXNDb250ZW50IjpbInNldHVwID0gLT5cclxuXHRjcmVhdGVDYW52YXMgNjAwLDYwMFxyXG5cdFxyXG5cdGFzc2VydCAoW2EsYl0gZm9yIGEsYiBpbiBbMTAsMjBdKSwgW1sxMCwwXSwgWzIwLDFdXVxyXG5cdGFzc2VydCAoYSBmb3IgYSBpbiBbMTAsMjBdKSwgWzEwLDIwXVxyXG5cclxuXHRhc3NlcnQgKFthLGJdIGZvciBhLGIgb2Yge2E6MTAsYjoyMH0pLCBbW1wiYVwiLDEwXSxbXCJiXCIsMjBdXVxyXG5cdGFzc2VydCAoYSBmb3IgYSBvZiB7YToxMCxiOjIwfSksIFtcImFcIixcImJcIl1cclxuXHJcblx0cHJpbnQgKGEgZm9yIGEgb2YgcmFuZ2UoMTAwMCkpXHJcblxyXG5cdCMgb2YgZ2VyIG55Y2tlbCBlbGxlciBpbmRleCJdfQ==
//# sourceURL=C:\github\SmallSketches\coffee\sketch.coffee