// Generated by CoffeeScript 1.11.1
var draw, setup;

setup = function() {
  return createCanvas(1800, 1000, WEBGL);
};

draw = function() {
  var i, j, k, l, len, len1, ref, ref1, results, t, x;
  t = frameCount;
  rotateX(mouseY * 0.005);
  rotateY(mouseX * 0.002);
  ref = range(5);
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    j = ref[k];
    push();
    x = 100 * sin(t * 0.001 + j);
    ref1 = range(80);
    for (l = 0, len1 = ref1.length; l < len1; l++) {
      i = ref1[l];
      translate(x, x, i * 0.1);
      rotateZ(t * 0.002);
      sphere(8);
    }
    results.push(pop());
  }
  return results;
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2luQ29zM0QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTaW5Db3MzRC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7U0FBRyxZQUFBLENBQWEsSUFBYixFQUFtQixJQUFuQixFQUF5QixLQUF6QjtBQUFIOztBQUNSLElBQUEsR0FBTyxTQUFBO0FBQ0wsTUFBQTtFQUFBLENBQUEsR0FBSTtFQUNKLE9BQUEsQ0FBUSxNQUFBLEdBQVMsS0FBakI7RUFDQSxPQUFBLENBQVEsTUFBQSxHQUFTLEtBQWpCO0FBQ0E7QUFBQTtPQUFBLHFDQUFBOztJQUNFLElBQUEsQ0FBQTtJQUNBLENBQUEsR0FBSSxHQUFBLEdBQU0sR0FBQSxDQUFJLENBQUEsR0FBSSxLQUFKLEdBQVksQ0FBaEI7QUFDVjtBQUFBLFNBQUEsd0NBQUE7O01BQ0UsU0FBQSxDQUFVLENBQVYsRUFBYSxDQUFiLEVBQWdCLENBQUEsR0FBSSxHQUFwQjtNQUNBLE9BQUEsQ0FBUSxDQUFBLEdBQUksS0FBWjtNQUNBLE1BQUEsQ0FBTyxDQUFQO0FBSEY7aUJBSUEsR0FBQSxDQUFBO0FBUEY7O0FBSksiLCJzb3VyY2VzQ29udGVudCI6WyIjIExPQzoxMiBmcmFtZUNvdW50IHB1c2ggcG9wIHJhbmdlIHJvdGF0ZVkgcm90YXRlWiBzaW4gc3BoZXJlIHRyYW5zbGF0ZVxyXG5zZXR1cCA9IC0+IGNyZWF0ZUNhbnZhcyAxODAwLCAxMDAwLCBXRUJHTFxyXG5kcmF3ID0gLT5cclxuICB0ID0gZnJhbWVDb3VudCBcclxuICByb3RhdGVYIG1vdXNlWSAqIDAuMDA1XHJcbiAgcm90YXRlWSBtb3VzZVggKiAwLjAwMiBcclxuICBmb3IgaiBpbiByYW5nZSA1XHJcbiAgICBwdXNoKClcclxuICAgIHggPSAxMDAgKiBzaW4gdCAqIDAuMDAxICsgalxyXG4gICAgZm9yIGkgaW4gcmFuZ2UgODBcclxuICAgICAgdHJhbnNsYXRlIHgsIHgsIGkgKiAwLjFcclxuICAgICAgcm90YXRlWiB0ICogMC4wMDJcclxuICAgICAgc3BoZXJlIDhcclxuICAgIHBvcCgpIl19
//# sourceURL=C:\github\SmallSketches\SinCos3D.coffee