// Generated by CoffeeScript 1.11.1
var draw, setup;

setup = function() {
  return createCanvas(1800, 1000, WEBGL);
};

draw = function() {
  var i, j, k, l, len, len1, ref, ref1, results, t, x;
  t = frameCount / 100;
  rotateX(mouseY * 0.005);
  rotateY(mouseX * 0.002);
  ref = range(5);
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    j = ref[k];
    push();
    x = 100 * sin(t * 0.001 + j);
    ref1 = range(80);
    for (l = 0, len1 = ref1.length; l < len1; l++) {
      i = ref1[l];
      translate(x, x, i * 0.1);
      rotateZ(t * 0.002);
      sphere(8);
    }
    results.push(pop());
  }
  return results;
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2luQ29zM0QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTaW5Db3MzRC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7U0FBRyxZQUFBLENBQWEsSUFBYixFQUFtQixJQUFuQixFQUF5QixLQUF6QjtBQUFIOztBQUNSLElBQUEsR0FBTyxTQUFBO0FBQ0wsTUFBQTtFQUFBLENBQUEsR0FBSSxVQUFBLEdBQVk7RUFDaEIsT0FBQSxDQUFRLE1BQUEsR0FBUyxLQUFqQjtFQUNBLE9BQUEsQ0FBUSxNQUFBLEdBQVMsS0FBakI7QUFDQTtBQUFBO09BQUEscUNBQUE7O0lBQ0UsSUFBQSxDQUFBO0lBQ0EsQ0FBQSxHQUFJLEdBQUEsR0FBTSxHQUFBLENBQUksQ0FBQSxHQUFJLEtBQUosR0FBWSxDQUFoQjtBQUNWO0FBQUEsU0FBQSx3Q0FBQTs7TUFDRSxTQUFBLENBQVUsQ0FBVixFQUFhLENBQWIsRUFBZ0IsQ0FBQSxHQUFJLEdBQXBCO01BQ0EsT0FBQSxDQUFRLENBQUEsR0FBSSxLQUFaO01BQ0EsTUFBQSxDQUFPLENBQVA7QUFIRjtpQkFJQSxHQUFBLENBQUE7QUFQRjs7QUFKSyIsInNvdXJjZXNDb250ZW50IjpbIiMgTE9DOjEyIGZyYW1lQ291bnQgcHVzaCBwb3AgcmFuZ2Ugcm90YXRlWiBzaW4gc3BoZXJlIHRyYW5zbGF0ZVxyXG5zZXR1cCA9IC0+IGNyZWF0ZUNhbnZhcyAxODAwLCAxMDAwLCBXRUJHTFxyXG5kcmF3ID0gLT5cclxuICB0ID0gZnJhbWVDb3VudCAvMTAwIFxyXG4gIHJvdGF0ZVggbW91c2VZICogMC4wMDVcclxuICByb3RhdGVZIG1vdXNlWCAqIDAuMDAyIFxyXG4gIGZvciBqIGluIHJhbmdlIDVcclxuICAgIHB1c2goKVxyXG4gICAgeCA9IDEwMCAqIHNpbiB0ICogMC4wMDEgKyBqXHJcbiAgICBmb3IgaSBpbiByYW5nZSA4MFxyXG4gICAgICB0cmFuc2xhdGUgeCwgeCwgaSAqIDAuMVxyXG4gICAgICByb3RhdGVaIHQgKiAwLjAwMlxyXG4gICAgICBzcGhlcmUgOFxyXG4gICAgcG9wKClcclxuIl19
//# sourceURL=C:\github\SmallSketches\SinCos3D.coffee