// Generated by CoffeeScript 1.11.1
var draw, setup;

setup = function() {
  return createCanvas(1800, 1000, WEBGL);
};

draw = function() {
  var i, j, k, l, len, len1, ref, ref1, results, x;
  rotateX(mouseY * 0.005);
  rotateY(mouseX * 0.002);
  ref = range(5);
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    j = ref[k];
    push();
    x = 100 * sin(frameCount * 0.001 + j);
    ref1 = range(80);
    for (l = 0, len1 = ref1.length; l < len1; l++) {
      i = ref1[l];
      translate(x, x, i * 0.1);
      rotateZ(frameCount * 0.002);
      sphere(8);
    }
    results.push(pop());
  }
  return results;
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2luQ29zM0QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTaW5Db3MzRC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7U0FBRyxZQUFBLENBQWEsSUFBYixFQUFtQixJQUFuQixFQUF5QixLQUF6QjtBQUFIOztBQUNSLElBQUEsR0FBTyxTQUFBO0FBQ0wsTUFBQTtFQUFBLE9BQUEsQ0FBUSxNQUFBLEdBQVMsS0FBakI7RUFDQSxPQUFBLENBQVEsTUFBQSxHQUFTLEtBQWpCO0FBQ0E7QUFBQTtPQUFBLHFDQUFBOztJQUNFLElBQUEsQ0FBQTtJQUNBLENBQUEsR0FBSSxHQUFBLEdBQU0sR0FBQSxDQUFJLFVBQUEsR0FBYSxLQUFiLEdBQXFCLENBQXpCO0FBQ1Y7QUFBQSxTQUFBLHdDQUFBOztNQUNFLFNBQUEsQ0FBVSxDQUFWLEVBQWEsQ0FBYixFQUFnQixDQUFBLEdBQUksR0FBcEI7TUFDQSxPQUFBLENBQVEsVUFBQSxHQUFhLEtBQXJCO01BQ0EsTUFBQSxDQUFPLENBQVA7QUFIRjtpQkFJQSxHQUFBLENBQUE7QUFQRjs7QUFISyIsInNvdXJjZXNDb250ZW50IjpbIiMgTE9DOjExIGZyYW1lQ291bnQgcHVzaCBwb3AgcmFuZ2Ugcm90YXRlWSByb3RhdGVaIHNpbiBzcGhlcmUgdHJhbnNsYXRlXHJcbnNldHVwID0gLT4gY3JlYXRlQ2FudmFzIDE4MDAsIDEwMDAsIFdFQkdMXHJcbmRyYXcgPSAtPlxyXG4gIHJvdGF0ZVggbW91c2VZICogMC4wMDVcclxuICByb3RhdGVZIG1vdXNlWCAqIDAuMDAyIFxyXG4gIGZvciBqIGluIHJhbmdlIDVcclxuICAgIHB1c2goKVxyXG4gICAgeCA9IDEwMCAqIHNpbiBmcmFtZUNvdW50ICogMC4wMDEgKyBqXHJcbiAgICBmb3IgaSBpbiByYW5nZSA4MFxyXG4gICAgICB0cmFuc2xhdGUgeCwgeCwgaSAqIDAuMVxyXG4gICAgICByb3RhdGVaIGZyYW1lQ291bnQgKiAwLjAwMlxyXG4gICAgICBzcGhlcmUgOFxyXG4gICAgcG9wKCkiXX0=
//# sourceURL=C:\github\SmallSketches\SinCos3D.coffee